[project]
name = "backend"
version = "0.1.0"
description = "Backend for mediashare written in Python with integration with Postgre using Alchemy"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "pyright>=1.1.411",
    "pytest>=9.1.1",
    "ruff>=0.16.4",
]
